### ISSUE TITLE
webshell questions

### ISSUE THREAD

**Issue by d3sh1n** [Udyz/proxyshell-auto#2]
Hi, I'm having some problems with webshell, I can use webshell normally with my administrator email address, then I added another admin user as administrator, then using that user I can survive webshell on the server, but executing commands won't work.

this is admin
![image](https://user-images.githubusercontent.com/78736442/130048168-4d810246-8bf3-4f6e-9f11-0c27ec8988f3.png)

this is administrator
![image](https://user-images.githubusercontent.com/78736442/130049067-556bd251-3bbc-44c8-a182-07ed4d37e282.png)

![image](https://user-images.githubusercontent.com/78736442/130049000-8be6d5c7-0545-4cac-82ea-8e973805c419.png)

**Comment by Udyz** [comment]
fixed... i was put wrong user sid admin (500) to send email and export from normal user so payload webshell didn't export
